#!/bin/bash

echo -n "Enter a number: "
read num

if [ "$num" -lt 10 ]; then
    echo "The number is smaller than 10."
elif [ "$num" -gt 10 ]; then
    echo "The number is larger than 10."
else
    echo "The number is equal to 10."
fi
